class ChatUser {
  String name;
  String imageURL;
  String message;
  String date;
  String time;
  bool seen;
  bool sent;
  bool received;
  int newMessages;
  ChatUser(
      {this.name,
      this.imageURL,
      this.message,
      this.date,
      this.time,
      this.seen,
      this.sent,
      this.received,
      this.newMessages});
}

List<ChatUser> dummyMsg = [
  new ChatUser(
      name: "Mohit kumar",
      imageURL: 'assets/images/person1.jpeg',
      message: "Hi where you been man!",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Mansi sharma",
      imageURL: 'assets/images/person2.jpeg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Harshit",
      imageURL: 'assets/images/person3.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Nitish rana",
      imageURL: 'assets/images/person4.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Akanksha rao",
      imageURL: 'assets/images/person5.jpeg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Abhijeet dokato",
      imageURL: 'assets/images/person6.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Abhishek roy",
      imageURL: 'assets/images/person7.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Kanchan",
      imageURL: 'assets/images/person8.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Hemant rana",
      imageURL: 'assets/images/person9.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Stwert little",
      imageURL: 'assets/images/person1.jpeg',
      message:
          "Hey did you have your yes yes yse yse syse yse yse yse shhhhhhhhhhhhhhh smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Daniella ron",
      imageURL: 'assets/images/person2.jpeg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Elizabeth",
      imageURL: 'assets/images/person3.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Peter Triggered",
      imageURL: 'assets/images/person4.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Royal blood",
      imageURL: 'assets/images/person5.jpeg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "outside row",
      imageURL: 'assets/images/person6.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Strongyman",
      imageURL: 'assets/images/person7.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Watcher man",
      imageURL: 'assets/images/person8.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
  new ChatUser(
      name: "Feely",
      imageURL: 'assets/images/person9.jpg',
      message: "Hey did you have your smartphone !",
      date: "11/20",
      time: "17:30",
      seen: true,
      sent: false,
      received: false,
      newMessages: 2),
];
